### PR TITLE
WIP: Unknown Prop Warning when rendering glamorous-primitive with custom styles

### LINKED ISSUE #8: "Unknown Prop Warning" when rendering glamorous-primitive with custom styles
When I render conditional styles with props on my glamorous-primitives I get the following error when running Jest tests:

```sh
Warning: Unknown props `empty`,`done` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in div (at index.js:91)
        in Button
       ...
```

the component I'm rendering looks like this:

```js
const Button = glam.text(
  {
    textTransform: 'uppercase',
    textAlign: 'center',
    fontSize: 14,
  },
  ({ empty, done }) => ({
    color: (empty || done) ? emptyTextColor : textColor,
  })
);
```

The failing test is here https://github.com/theinterned/One-Big-Thing/blob/1-text-entry-component/src/App.test.js

### PR DESCRIPTION
**Pull request by theinterned**
This is work to resolves #8 but it isn't working yet

### CODE REVIEW

**Comment by theinterned** [comment]
I have been able to create a test that recreates the issue [native.test.js#L130](https://github.com/theinterned/glamorous-primitives/blob/79ed8e7ed9b6b896699d38277100dbd88fd2c53d/__tests__/native.test.js#L130)

But I am at a loss for how to fix it. It looks like there is some funny business to do with `rootEl`. 

The culprit seems to come in [split-props.js#L10]( https://github.com/theinterned/glamorous-primitives/blob/79ed8e7ed9b6b896699d38277100dbd88fd2c53d/src/constructor/split-props.js#L10 ) which is looking for a `rootEl` of type string to figure out what props to pass on. As far as I can tell, `rootEl` is never a string. 

Maybe @nitin42 you can offer some suggestions on how to fix this?

**Comment by nitin42** [comment]
Thanks for the PR. I'll look into this (will possibly resolve) next week. Sorry for the delay, I've been busy a lot with wrapping up my final semester and maintaining different projects (doesn't mean that this project is dead or will not be maintained). I hope you understand! But thank you so much for the WIP pull request. This will come handy. Have a nice day!

**Comment by theinterned** [comment]
I think the problem is that the implementation is copied from glamorous-native which doesn't care about React elements. I wonder if we could check for the core [React `HTMLNodeType`](https://github.com/facebook/react/blob/725c054d4d5d07c5c553a1ca724b01f2e6a43c5d/packages/react-dom/src/shared/HTMLNodeType.js) instead?

**Comment by theinterned** [comment]
This PR is quite stale, and maybe the project is no longer under development? Closing.

**Pull request closed without merging**
